#!/usr/local/bin/perl -Tw

# Author:        jgrg
# Group:         anacode
# Maintainer:    jgrg
# Last modified: $Date: 2011-05-13 12:11:26 $
# Id:            $Id: nph-test,v 1.20.2.9 2011-05-13 12:11:26 jh13 Exp $
# Source:        $Source: /tmp/ENSCOPY-ENSEMBL-OTTER/scripts/apache/Attic/nph-test,v $

use strict;
use warnings;

use SangerPaths qw{ core bioperl123 ensembl62 otter52 };
use SangerWeb;

use Bio::Otter::ServerScriptSupport;

my $server = Bio::Otter::ServerScriptSupport->new;
my $web = SangerWeb->new({
    'cgi'   => $server,
    });

my $user = $web->username;

my $env = "ENV:\n";
foreach my $var (sort keys %ENV) {
    $env .= sprintf "%24s  %s\n", $var, $ENV{$var};
}

$env .= "\nCGI->nph=".($server->nph)."\n\$0=$0\n";

$env .= "\nCGI param:\n";
foreach my $var ($server->param) {
    $env .= sprintf "%24s  %s\n", $var, $server->param($var);
}

$env .= sprintf "\nSangerWeb cgi = %s\n", $web->cgi;
$env .= sprintf "\nSangerWeb username = %s\n", $web->username;

my $dbh = DBI->connect("DBI:mysql:database=pipe_human;host=otterslave;port=3322", "ottro", undef);
$env .= "CONNECTED $dbh";

if ($server->local_user) {
    $server->send_response($env);
} else {
    $server->send_response("You are an external user\n");
}
